# Generated by Django 3.2.20 on 2023-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'article_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleCOI',
            fields=[
                ('coi_id', models.AutoField(primary_key=True, serialize=False)),
                ('coi_text', models.TextField()),
            ],
            options={
                'db_table': 'article_coi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'article_grant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrantInfo',
            fields=[
                ('grant_id', models.AutoField(primary_key=True, serialize=False)),
                ('grant_val', models.TextField()),
            ],
            options={
                'db_table': 'grant_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PubmedAffiliation',
            fields=[
                ('affil_id', models.AutoField(primary_key=True, serialize=False)),
                ('norm_affil', models.TextField()),
            ],
            options={
                'db_table': 'pubmed_affiliation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PubmedArticle',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('journal_title', models.TextField()),
                ('doi', models.CharField(max_length=500)),
                ('pubmed_link', models.TextField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'pubmed_article',
                'ordering': ['journal_title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PubmedAuthor',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.TextField()),
            ],
            options={
                'db_table': 'pubmed_author',
                'managed': False,
            },
        ),
    ]
